"""
:file: processResults.py

Processes the reports generated by the Mosquito model.

:author: clayton pruitt
:date: 12/2/2019
"""

import matplotlib.pyplot as plt
import os

# used to determine output file path in plotAndOutput()
file_path = os.path.dirname(__file__)

# format used for plots
fmt = 'ro'
# current plot index
pi = 0

def plotAndOutput(title, data, labels):
    """
    Creates and outputs a standardized plot to the '/reports' directory.

    :param title: the title of the plot
    :param data: tuple where data[0] is the x data and data[1] is the y data
    :param labels: tuple where labels[0] is the label for the x-axis and labels[1] is the label for the y-axis
    :return: outputs a .png to '/reports/ directory
    """
    global pi
    plt.figure(pi)
    plt.plot(data[0], data[1], fmt)
    plt.xlabel(labels[0])
    plt.ylabel(labels[1])
    plt.title(title, fontsize = 20)
    os.chdir(file_path)
    plt.savefig("../reports/modelgraph" + str(pi) + ".png")
    pi += 1
